### ISSUE TITLE
Hi updates!

### ISSUE THREAD

**Issue by Stellaki** [radionics/OpenSourceRadionics#1]
Hi, I like to pull a request!

**Comment by radionics** [comment]
See how to **clone** and **pull** a repository: 

- https://try.github.io/levels/1/challenges/1
- https://www.youtube.com/watch?v=rgmDhNLQ3yU
- https://www.youtube.com/watch?v=73I5dRucCds

**Comment by Stellaki** [comment]
Thank you!
