### ISSUE TITLE
features to embed the Aether in a case or analog device

### ISSUE THREAD

**Issue by Stellaki** [radionics/OpenSourceRadionics#18]
from the group 
to implement features necessary to embed the Aether in a case or analog device.

regards!
Stellaki

**Comment by radionics** [comment]
This issue needs more details.

**Comment by radionics** [comment]
I will write new issues regarding the case embedding. But this one does not contain any details, therefore I close it.

**Comment by Stellaki** [comment]
I think this one can be a connection of the Aetherone with an analoge radionics device. How  can we use a pin for that in order to bring the broadcast to the input of an analoge device. But perhaps you already implemented this future at the moment you programmed the pin 7 and 8 for the coil . If we make the coil with long ends, we can also place it on the input of an analoge redionics device.. and you are ready to broadcast  from there.
