### ISSUE TITLE
Klik function selection file form database check 

### ISSUE THREAD

**Issue by Stellaki** [radionics/OpenSourceRadionics#20]
we have now the function of checking for all items in the database folder, in order to analyze which database could possibly contain the required information and rate.
I wonder 🤔 if the Aetherone can handle another function following the one of . 
Like selecting a file with a click from this list to use it directly for analysis. 😎🤗

kind regards
Stella

**Comment by radionics** [comment]
Yes this is possible, and it was also my thought (following the logic workflow)

**Comment by Stellaki** [comment]
this has already been implemented in the app

**Comment by Stellaki** [comment]
this one is now in the functions!

**Comment by radionics** [comment]
Implemented
