### ISSUE TITLE
WARNING: java.lang.IllegalArgument

### ISSUE THREAD

**Issue by Stellaki** [radionics/OpenSourceRadionics#8]
Hi radionics, 
see all the septs below we see a warning in the console, that it is about the control broadcaster. 
 I think this is something from the broadcasting line. 
text from the console:
<<<....ControlP5 2.2.6 infos, comments, questions at http://www.sojamo.de/libraries/controlP5
controlEvent clear
controlEvent grounding
controlEvent connect
controlEvent select data
controlEvent analyze
controlEvent general vitality
controlEvent broadcast
**_Jul 29, 2018 12:37:59 PM controlP5.ControlBroadcaster invokeMethod
WARNING: java.lang.IllegalArgumentException: wrong number of arguments_**

Thanks for your attention. I’m looking forward to your reply.

Kind regards, 
Stellalki

**Comment by radionics** [comment]
This is a ControlP5 issue and needs to be fixed in the ControlP5 project.

**Comment by radionics** [comment]
CP5 issue. I close it, because this cannot be fixed here.
